language: python
python:
 - "2.6"
 - "2.7"
 #- "3.2" # Someday..
install: python setup.py install
script: python setup.py test
notifications:
    email: true
    irc:
        - "irc.freenode.net#threebean"
    on_success: change
    on_failure: change
