---
- name: Install RPM packages
  dnf:
    name:
    - gcc
    - libffi-devel
    - libpq-devel
    - krb5-devel
    - python3-cryptography
    - python3-devel
    - python3-pip
    - python3-virtualenv
    state: present

- name: Install the .bashrc
  copy:
    src: bashrc
    dest: /home/vagrant/.bashrc
    mode: 0644
    owner: vagrant
    group: vagrant

# - name: Install poetry Python package
#   command: pip install poetry
# 
# - name: install python deps
#   become_user: vagrant
#   command:
#     cmd: poetry install
#     chdir: fedbadges

- name: prepare virtualenv
  file:
    path: /opt/venv
    state: directory
    owner: vagrant
    group: vagrant

- name: install some python build deps
  become_user: vagrant
  pip:
    virtualenv: /opt/venv
    name: cython

- name: install python deps
  become_user: vagrant
  pip:
    chdir: fedbadges
    editable: true
    virtualenv: /opt/venv
    name: .

- name: Install the configuration file
  copy:
    src: config.toml
    dest: /etc/fedora-messaging/fedbadges.toml
    owner: root
    group: vagrant
    mode: 0640

- name: Install the systemd unit files
  copy:
    src: fedbadges.service
    dest: /etc/systemd/system/fedbadges.service
    mode: 0644

- name: Start the service using systemd
  systemd:
    state: started
    name: fedbadges
    daemon_reload: yes
    enabled: yes
