---
- name: Install RPM packages
  dnf:
    name:
    - gcc
    - libffi-devel
    - libpq-devel
    - krb5-devel
    - python3-cryptography
    - python3-devel
    - python3-pip
    - python3-virtualenv
    state: present

- name: Install the .bashrc
  copy:
    src: bashrc
    dest: /home/vagrant/.bashrc
    mode: 0644
    owner: vagrant
    group: vagrant

# - name: Install poetry Python package
#   command: pip install poetry
# 
# - name: install python deps
#   become_user: vagrant
#   command:
#     cmd: poetry install
#     chdir: fedbadges

- name: prepare virtualenv
  file:
    path: "{{ venv }}"
    state: directory
    owner: vagrant
    group: vagrant

- name: install some python build deps
  become_user: vagrant
  pip:
    virtualenv: "{{ venv }}"
    name: cython

- name: install python deps
  become_user: vagrant
  pip:
    chdir: "{{ item }}"
    editable: true
    virtualenv: "{{ venv }}"
    name: .
  loop:
    - tahrir-api
    - tahrir
    - fedbadges

- name: Install the configuration file
  copy:
    src: config.toml
    dest: /etc/fedora-messaging/fedbadges.toml
    owner: root
    group: vagrant
    mode: 0640

- name: Copy Tahrir development.ini config file
  copy:
    src: development.ini
    dest: /home/vagrant/development.ini
    owner: vagrant
    group: vagrant
    mode: 0640

- name: Copy Tahrir secret.ini config file
  copy:
    src: secret.ini
    dest: /home/vagrant/secret.ini
    owner: vagrant
    group: vagrant
    mode: 0640

- name: Initialize the Tahrir DB
  become_user: vagrant
  command: "{{ venv }}/bin/initialize_tahrir_db /home/vagrant/development.ini"

- name: Install the systemd unit files
  copy:
    src: "{{ item }}.service"
    dest: /etc/systemd/system/tahrir.service
    mode: 0644
  loop:
    - fedbadges
    - tahrir

- name: Start the service using systemd
  systemd:
    state: started
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
  loop:
    - fedbadges
    - tahrir
